### PR TITLE
Get access to message payload

### LINKED ISSUE #210: Get access to message payload
We may face the case where an `async.Message` fails to be decoded. 
In this case, we would like to have the possibility to have access to the message payload to log it. What about adding the following method in the `async.Message` structure:
* `Payload() []byte`

### PR DESCRIPTION
**Pull request by teivah**
Closes #210.

### CODE REVIEW

File: component/async/kafka/kafka.go [hunk 1]
```diff
@@ -118,18 +118,23 @@ func (m *message) Ack() error {
...
-
 // Nack signals the producing side an erroring condition or inconsistency.
 func (m *message) Nack() error {
 	messageConfirmationCountInc("NACK")
 	trace.SpanError(m.span)
 	return nil
 }
 
+// Source returns the kafka topic where the message arrived.
+func (m *message) Source() string {
```
Comment (teivah) [inline component/async/kafka/kafka.go:129]: I just swapped Source() and Nack() so that we have the same order in all the implem & the interface

**Review by drakos74 — DISMISSED** [review]
nice! I always had this urge to make this change. Happy that the use-case came up :)

File: component/async/component_test.go [hunk 2]
```diff
@@ -450,6 +450,10 @@ func (mm *mockMessage) Source() string {
 	return ""
 }
 
+func (mm *mockMessage) Payload() []byte {
```
Comment (mantzas) [inline component/async/component_test.go:453]: Is there a test to add this as a check?

**Review by mantzas — CHANGES_REQUESTED** [review]

**Review by mantzas — APPROVED** [review]

**Review by drakos74 — APPROVED** [review]

**Review by fpapadopou — APPROVED** [review]

**Comment by fpapadopou** [comment]
🚢
